# Generated by Django 5.1.6 on 2025-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal", models.CharField(max_length=100)),
                ("food", models.CharField(max_length=100)),
                ("calories", models.IntegerField()),
                ("exercise", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="DailyReport",
        ),
    ]
